name: Deploy to Nginx

on:
  schedule:
    - cron: '0 0 * * *'  # Schedule for daily deployment at 12:00 AM UTC

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Add build steps if necessary
      # - name: Build
      #   run: npm install && npm run build

      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.22 }}
          script: |
            cd /path/to/your/nginx/root
            git pull origin main  # Replace 'main' with your branch name
            # Add any additional deployment steps (e.g., restarting Nginx)
            # systemctl restart nginx
